CREATE DATABASE MTPI;

USE MTPI;
CREATE TABLE USERS(
	ID_USER INT AUTO_INCREMENT NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	NAME_USER VARCHAR(60) NOT NULL,
	PASS varchar(100) NOT NULL,
	ROL varchar(20) NOT NULL,
	PRIMARY KEY(ID_USER)     
);

CREATE TABLE PRODUCTS(
	ID_PRODUCT INT AUTO_INCREMENT NOT NULL,
    NAME_PRODUCT VARCHAR(50) NOT NULL,
    BRAND_PRODUCT VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    AVAILABILITY BOOLEAN NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE INT NOT NULL,
    PRIMARY KEY(ID_PRODUCT)
);

CREATE TABLE CAR_SHOP(
	ID_CARSHOP INT AUTO_INCREMENT NOT NULL,
    ID_USER INT NOT NULL,
    ID_PRODUCT INT NOT NULL,
    ID_ORDER INT ,
    QUANTITY INT NOT NULL,
    TOTAL INT NOT NULL,
    PRIMARY KEY(ID_CARSHOP, ID_PRODUCT)
);

CREATE TABLE ORDERS(
	ID_ORDER INT AUTO_INCREMENT NOT NULL,
	ID_USER INT NOT NULL,
    DATA_ORDER DATE NOT NULL,
    PRIMARY KEY(ID_ORDER, ID_USER)
);

ALTER TABLE CAR_SHOP
	ADD FOREIGN KEY (ID_USER)
    REFERENCES USERS(ID_USER)
    ON UPDATE CASCADE;
    
ALTER TABLE CAR_SHOP    
	ADD FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCTS(ID_PRODUCT)
    ON UPDATE CASCADE;
    
ALTER TABLE CAR_SHOP
	ADD FOREIGN KEY (ID_ORDER)
    REFERENCES ORDERS(ID_ORDER)
    ON UPDATE CASCADE;
    

ALTER TABLE ORDERS
	ADD FOREIGN KEY (ID_ORDER)
    REFERENCES USERS(ID_USER)
    ON UPDATE CASCADE;
